### ISSUE TITLE
[enhancement] configMergeLoader should not omit errors implicitly

### ISSUE THREAD

**Issue by zjx20** [ngx-config/merge-loader#3]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

As the recent refactor, `ConfigMergeLoader` becomes more powerful than before. I think `ConfigMergeLoader` should not omit errors implicitly, because the behavior was designed for the original purpose of `ConfigMergeLoader`.

Therefor, I'm suggesting the following changes:

1. Move the error-tolerance capability to `ConfigHttpLoader`, say:

    ```
    export class ConfigHttpLoader implements ConfigLoader {
      constructor(private readonly http: Http,
                  private readonly endpoint: string = '/config.json',
                  private readonly ignoreError: boolean = false) {
        ...
      }
      ...
    }
    ```

2. Simply the implementation of `mergeParallel()` in `ConfigMergeLoader`, by using `concat()` to replace `onErrorResumeNext()` and removing some code.

I currently don't have time to do this, I will finish it when I'm free. (@fulls1z3 maybe you can do that for me?)

**Comment by fulls1z3** [comment]
Hi @zjx20, I've thought about this functionality and I believe we have to add this `ignoreError` param on the abstract class `ConfigLoader`.

We currently have more than just the `http-loader`: the `fs-loader`, the `static-loader`, and possibly any custom implementation of `ConfigLoader`.

I don't have enough time this week, but I think in the upcoming weeks I'll probably have.

**Comment by fulls1z3** [comment]
Closing the issue, the discussion will take place on https://github.com/ngx-config/core/issues/15
