### ISSUE TITLE
[question] unable to get the app configs keys for angular4

### ISSUE THREAD

**Issue by chanvir-pm** [ngx-config/merge-loader#4]
hey ,
I am trying to read json configs with parallel execution mode, but im getting following error: 
polyfills.bundle.js:3133 Unhandled Promise rejection: No setting found with the specified key [system]! ; Zone: <root> ; Task: Promise.then ; Value: Error: No setting found with the specified key [system]!

/***my function*/
  getApiURL(): string {
       

        console.log( this.config ); //
[app-configs.zip](https://github.com/ngx-config/merge-loader/files/1061735/app-configs.zip)

        let url: string = this.config.getSettings( 'system' ).applicationUrl;

       
        return url;
    }

**Comment by fulls1z3** [comment]
@chanvir-pm thanks for your detailed instructions, this happens either there is no setting with the key `system` at the moment the app invokes the `config.getSettings` method.

For instance, if the calling method is invoked before the ngx-cache retrieves the configuration settings, it's possible to have this issue. Can you check this please?
